llm-d/llm-d-benchmark

- .github/actions/markdown-link-checker/action.yaml
- README.md
- quickstart-k8s/README.md
- quickstart-k8s/analyze_results.py
@maugustosilva ptal, ty! This fixes the templates to remove broken links and fixes paths in README
> fix broken links in quickstart templates & docs typo

- quickstart-existing-stack-benchmark/analysis-job.yaml
- quickstart-existing-stack-benchmark/benchmark-job.yaml
- quickstart-existing-stack-benchmark/compare-stacks/benchmark-job.yaml
- quickstart-existing-stack-benchmark/compare-stacks/compare-analysis-job.yaml
- quickstart-existing-stack-benchmark/compare-stacks/retrieve-compare.yaml
- quickstart-existing-stack-benchmark/resources/benchmark-env.yaml
- quickstart-existing-stack-benchmark/retrieve.yaml
- util/patches/fmperf.patch
Quickstart was failing in Kubernetes due to runAsNonRoot being set.
OpenShift runs as non-root by default, no need to set this - setting `runAsNonRoot` causes an error in Kubernetes `"Error: container has runAsNonRoot and image will run as root"`. The correct way to run as non-root that is compatible with OpenShift and Kubernetes is to set non-root user in the Dockerfile. OpenShift will ignore the UID and run with an arbitrary non-root UID. Kubernetes will honor the UID and run as what's set in the Dockerfile.
> quickstart: fix perms in jobs, set default env llm-d

- setup/env.sh
This PR adds missing `-o json` arguments to a kubectl/oc command requiring JSON output.
> Add missing json output flag

- setup/env.sh
`oc get nodes -o json | jq -C -r '.items[].metadata.annotations.[]' | grep nvidia.com/gpu.product`
```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.items[].metadata.annotations.[]
jq: 1 compile error
```
> jq and affinity typo

- setup/run.sh
- Fixed lookup when name is substring of multiple pods/services
- Fixed typo in env var name
> fix lookup for existing deployment

- setup/run.sh
Detect conda root location (e.g., when installed on user's home)
- need to verify on mac
- consider calling step 01 to install conda if missing. (maybe just add to failure notification)
> Allow different conda root locations

- setup/run.sh
- Currently, sets `LMDBENCH_HARNESS_ACCESS_RESULTS_POD_NAME` incorrectly with verbose or dry_run on.
- (Unrelated:) fix typo for variable ` $copy_analisys_cmd`
> fix LMDBENCH_HARNESS_ACCESS_RESULTS_POD_NAME when verbose is set

- workload/harnesses/vllm-benchmark-llm-d-benchmark.sh
- workload/profiles/vllm-benchmark/random_1k_concurrent_10-1_ISL-OSL.yaml.in
Additionally added an example workload (vllm-benchmark) which allows "parameter sweep"
> Additional fixes for "parameterless" CLI options on vllm-benchmark

- build/Dockerfile
While `llm-d-benchmark.sh` checks out the right branch if different from the default, it should also reinstall the python packages.
*note:* verify that the installs of the default repos works as intended. Currently, some do not install for the checked-out branch.
> Install python again after changing repo/branch

- workload/harnesses/inference-perf-llm-d-benchmark.sh
Fix typo in path to inference-perf config directory (inferenece-perf → inference-perf)
> Fix typo in inference-perf config path

- workload/harnesses/fmperf-llm-d-benchmark.py
using kube async python library to remove a time.wait(30) hardcoded in fmperf benchmark script in function that waits for eval job to be done, also removing hardcoded timeout checking. It uses a stream that can be continuously checked asynchronously provided by the kube aync api with ```w = k8s_async_watch.Watch()
async with w.stream( ...
```
> kubeasync addition to remove time.wait(30)

- workload/harnesses/fmperf-llm-d-benchmark.py
Change default so each `fmperf` evaluate job gets a different name.
> Use unique job_id by default

- build/Dockerfile
- build/llm-d-benchmark.sh
- setup/env.sh
- setup/functions.sh
- setup/teardown.sh
- workload/harnesses/fmperf-llm-d-benchmark.py
- workload/harnesses/guidellm-llm-d-benchmark.sh
- workload/harnesses/nop-llm-d-benchmark.py
- workload/harnesses/vllm-benchmark-llm-d-benchmark.sh
With this PR all harnesses, whether python or bash, will add the used workload profile (an `yaml` file) and a `stdout.log` to the results directory.
Also, fixed a longstanding bug with the moving of the `LLMDBENCH_CONTROL_WORK_DIR` when `./setup/standup.sh` was called with all the steps
> [Run] feat: ensure all harnesses work properly and output the same data

- setup/functions.sh
- setup/run.sh
- setup/steps/09_smoketest.sh
Introduces the function `get_model_name_from_pod`. This function is the used to get the served model name from the `pod` or `service` and the obtained name is compared with `LLMDBENCH_DEPLOY_CURRENT_MODEL`.
Used both on `smoketest` (step `9` of `standup.sh`) and `run.sh`
> [Setup][Run] feat: automatically detected the served model name

- build/Dockerfile
- build/llm-d-benchmark.sh
- build/requirements-analysis.txt
- workload/harnesses/vllm-benchmark-llm-d-benchmark.sh
- workload/report/convert.py
- workload/report/schema.py
This is the next step in implementing #162, which incorporates a post-processing step to the vLLM benchmark harness creating a report in the standardized benchmarking format.
> Add universal report conversion step to vLLM benchmark harness

- workload/harnesses/guidellm-llm-d-benchmark.sh
- workload/report/README.md
- workload/report/convert.py
- workload/report/report_json_schema.json
- workload/report/schema.py
This implements conversion to the standard benchmark report format with the GuideLLM harness for #162 (and #216).
> Add universal report conversion post-processing step to GuideLLM harness

- workload/report/convert.py
Fix improper type hints using `any` with `Typing.Any`.
> Fix improper use of `any`

- setup/steps/04_ensure_model_namespace_prepared.py
Incorrect check for dry run. The wait for download to complete does not wait. this causes problems later by interactions in other steps.
Fixes https://github.com/llm-d/llm-d-benchmark/issues/282.
> [emergency fix] fix check for dry run

- setup/steps/04_ensure_model_namespace_prepared.py
If attempt to start vllm as non-root without these changes, it won't have file read/write permissions it needs.
> change condition for adm policy

- scenarios/precise-prefix-cache-aware.sh
Example scenario `precise-prefix-cache-aware.sh` is now broken.
Remove `_epp` suffix from endpoint.
> tiny fix to example scenario

- setup/functions.py
- setup/functions.sh
Make sure that the same model can be deployed in different namespaces.
Inability to do so is regression from changes to support llm-d-infra v0.3.0.
There is a naming conflict with the `ClusterRole` and `ClusterRoleBinding` (created by gaie)
Fixed by including namespace in hash used to define names of objects.
> re-enable multiple ns

- build/Dockerfile
Pulls in the fix for CPU utilization issue (https://github.com/kubernetes-sigs/inference-perf/pull/204) when there are many workers at low QPS. Should also address TTFT differences at low QPS on a larger machine.
> Update inference-perf to include CPU utilization fix

- experiments/pd-disaggregation.yaml
- Reduce number of `max-concurrency` values to sweep, greatly reducing run time
- Add all combinations of P/D with 16 accelerators where TP of decode is greater than TP of prefill
- Only test standalone sweeps with a single replica
> Update PD-disagg well-lit path experiment

- config_explorer/Home.py
- config_explorer/README.md
Clarify steps to installing the UI of config explorer, since it's separate from the lib but requires installing lib first.
> Clarify installation steps for config explorer

- workload/report/convert.py
- workload/report/schema.py
It appears Inference Perf records all metrics in seconds.
@achandrasekar please make sure I've got all the units correct and haven't missed anything, thanks.
> Correct units captured by Inference Perf

- build/Dockerfile
Update to the latest commit in [v0.2.0](https://github.com/kubernetes-sigs/inference-perf/releases/tag/v0.2.0)
> Updated inference-perf harness to v0.2.0

- analysis/nop-analyze_results.py
- workload/harnesses/nop-llm-d-benchmark.py
- workload/report/convert.py
This PR relates to `nop` harness on an vLLM standalone server. It adds/changes some of the categories and adds the process name to the report.
The new analysis output looks like this:
```
Scenario
Harness       : nop
Load Format   : auto
Sleep Mode On : True
Model         : ibm-granite/granite-3.2-8b-instruct
Engine
Name         : quay.io/manoelmrqs/vllm-openai-custom:0.10.2
Version      : 0.1.dev9987+ge61eb5e09
Args         : {'enable_sleep_mode': True, 'gpu_memory_utilization': 0.95, 'max_model_len': 16384, 'model': 'ibm-granite/granite-3.2-8b-instruct', 'model_loader_extra_config': {'enable_multithread_load': True, 'num_threads': 8}, 'model_tag': 'ibm-granite/granite-3.2-8b-instruct'}
Benchmark
Start                    : 2025-09-30T17:21:04.432381+00:00
Elapsed(secs)            : …
```
> Add new categories and process name to nop harness result report
