llm-d/llm-d-benchmark

setup/env.sh
setup/steps/04_ensure_model_namespace_prepared.sh
setup/steps/06_deploy_vllm_standalone_models.sh

Additionally, fix an error when there is `/` on model name.

[Setup/standup] bugfix: fix the default tag for container image

---

analysis/analyze_results.py
build/Dockerfile
setup/env.sh
setup/run.sh
setup/steps/04_ensure_model_namespace_prepared.sh
setup/steps/07_invoke_llm-d-deployer.sh
setup/teardown.sh
util/patches/llm-d-deployer.patch

Will create a new image (required) `v0.1.0`
Additionally, fixed a long standing bug related to Kubernetes context being lost.

[Analysis] feat: provide support for remote execution of analyze_results.py

---

OWNERS
setup/env.sh

Additionally, bumped the image tag

chore: change owners file

---

README.md

[GARDENING]: Tiny fixes on the README file

---

setup/env.sh

Simple bug fix addressing a missing $ in a Bash variable

Add missing $ to Bash variable

---

build/Dockerfile

Remove the copy of the stale pod_log_response.txt

---

setup/steps/07_invoke_llm-d-deployer.sh

The cli `--gateway` now has explicitly specified on the command line (`invoke_llm-d-deployer.sh`)

[Setup/standup] New changes in `llmd-installer.sh` broke deployment.

---

analysis/inference-perf-analyze_results.sh
build/Dockerfile
workload/profiles/inference-perf/chatbot_sharegpt.yaml.in
workload/profiles/inference-perf/chatbot_synthetic.yaml.in
workload/profiles/inference-perf/code_completion_synthetic.yaml.in
workload/profiles/inference-perf/summarization_synthetic.yaml.in

Analysis produces the following charts: https://github.com/kubernetes-sigs/inference-perf?tab=readme-ov-file#analysis

Add inference-perf analysis to generate charts

---

README.md

The pull request fixes a broken hyperlink in `README.md`.

fix(docs): fix a broken hyperlink in README.md

---

workload/harnesses/fmperf-llm-d-benchmark.py

Move the result csv files from `/requests/{model name}`, where fmperf saves them to `/requests/LLMDBENCH_RUN_EXPERIMENT_RESULTS_DIR`, which includes the experiment ID.
Locate the results file by parsing the LMBench logs.

move results to directory with experiment ID

---

setup/install_deps.sh

enables users to install deps required for setup and specifcally step 0 in setup.https://github.com/llm-d/llm-d-benchmark/issues/149

script to install common deps, with support for linux and mac

---

analysis/nop-analyze_results.py
workload/harnesses/nop-llm-d-benchmark.py
workload/harnesses/nop-llm-d-benchmark.sh

Separation of `nop` harness and analysis. The harness saves  a csv file and the vllm log in the results directory. The analysis saves a table file in the analysis directory.

Add vllm logs to nop harness results, move txt file to analysis dir

---

workload/report/schema.py

First part of #162, creates a definition for report format, including validation (importing data not adhering to schema or having invalid entries will be rejected with corresponding errors) and JSON schema generation.
This follows the proposal at https://github.com/kubernetes-sigs/inference-perf/issues/124

Add report definition

---

setup/functions.sh
setup/steps/06_deploy_vllm_standalone_models.sh
setup/steps/08_deploy_via_modelservice.sh

Logs are automatically captured under
`${LLMDBENCH_CONTROL_WORK_DIR}/setup/logs/`

[Setup] feat: resolves #194 by capturing llm-d/vllm pod logs

---

setup/functions.py
setup/functions.sh

See huggingfac_hub release note: https://github.com/huggingface/huggingface_hub/releases/tag/v0.34.0

Update huggingface cli syntax to huggingface_hub>v0.34.0

---

analysis/nop-analyze_results.py
scenarios/kubernetes_A100_standalone_llama-3b.sh
workload/harnesses/nop-llm-d-benchmark.py
workload/report/convert.py
workload/report/schema.py

Changed `nop` harness to call 'convert.py' that will convert its output to the universal format.
Changed `convert.py` to convert `nop` harness result to universal format.
Changed `nop` analysis to read from universal format.

Add universal report format to nop harness

---

setup/steps/07_deploy_setup.py

- Add setup/steps/07_deploy_setup.py as Python conversion of bash script
- Follows BASH_TO_PYTHON_CONVERSION.md guidelines
- Maintains same functionality with improved error handling and logging
Fixes #267

Convert step 07 to Python

---

scenarios/examples/inference-scheduling.sh
scenarios/examples/pd-disaggregation.sh
scenarios/examples/precise-prefix-cache-aware.sh
setup/functions.sh
setup/run.sh
setup/steps/08_deploy_gaie.py
setup/steps/10_smoketest.sh

Also fixed two additional bugs
Finally, testing "inferencepool" creation during smoketest

[Setup] Ensure well-lit paths can be deployed

---

experiments/inference-scheduling.yaml

Update experiments file for inference scheduling well-lit path

---

setup/steps/06_deploy_vllm_standalone_models.py
workload/report/convert.py

- Add missing argument to function
- Update environment variable to get model name from within harness pod

Assorted small bug fixes

---

scenarios/examples/gpu.sh
setup/functions.sh
setup/steps/00_ensure_llm-d-infra.py

Added a more illustrative example for gpus on `scenarios`
Fixed a minor bug when running backups on `e2e`

[Standup] Added a more informative error message when attempting to invoke the "capacity planner"
